# .github/workflows/publish.yml

name: Publish
on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
  push:
    tags:
      - 'v*' # or '1.*' depending on versioning
      
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Publish to MavenCentral
        run:  ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      # - name: Push release to iOS Cocoapods Repo
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      #     git clone --depth=1 --branch=main https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com:MamoonaMahmood/ios-cocoapods-host.git temp-repo

      #     rm -rf temp-repo/*
      #     cp -R shared/cocoapods/publish/release/* temp-repo/

      #     cd temp-repo
      #     git add .
      #     git commit -m "Update Cocoapods release from $GITHUB_REPOSITORY $GITHUB_REF"
      #     git push origin main

      - name: Set up SSH for Cocoapods Repo Push
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KMMBRIDGE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Publish KMMBridge
        run: ./gradlew publishKmmBridge
